version: '3.3'
services:
  nginx:
    image: nginx
    networks:
      - deltares
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80" # nginx is exposed to 8003 outside
    depends_on:
      - rest
      - static
    command: [nginx-debug, '-g', 'daemon off;']
  rest:
    image: registry-sdc.argo.grnet.gr/sdc-visualization-service:build-2020-02-10T1203
    networks:
      - deltares
    restart: always
  static:
    image: registry-sdc.argo.grnet.gr/sdc-visualization-static:build-2020-02-10T1645
    networks:
      - deltares
    restart: always
networks:
  deltares:
    driver: "bridge"

volumes:
  storage:
    driver: local
