version: '3.3'
services:
  nginx:
    image: nginx
    networks:
      - deltares
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      # nginx is exposed to 8003 outside
      - 80
    depends_on:
      - rest
      - static
    command: [nginx-debug, '-g', 'daemon off;']
  rest:
    image: sdc-visualization-service
    networks:
      - deltares
    restart: always
    environment:
      - VIZ_URL=https://jellyfish.argo.grnet.gr/viz
      - DASHBOARD_URL=https://sdc-test.argo.grnet.gr
  static:
    image: sdc-visualization-static
    networks:
      - deltares
    restart: always
networks:
  deltares:
    driver: "bridge"

volumes:
  storage:
    driver: local
